package com.example.ui.util

object Localization {

    enum class Language(val code: String, val label: String) {
        VN("VN", "Tiếng Việt"),
        EN("EN", "English")
    }

    private val stringsVN = mapOf(
        "app_title" to "KARAOKE STUDIO",
        "app_subtitle" to "Trình làm Karaoke chuyên nghiệp",
        "new_project" to "Dự án mới",
        "new_project_sub" to "Bắt đầu tạo Video hoặc file MIDI/KAR mới",
        "recent_projects" to "DỰ ÁN GẦN ĐÂY",
        "projects_count" to "dự án",
        "no_projects_title" to "Chưa có dự án nào",
        "no_projects_desc" to "Nhấp 'Dự án mới' để bắt đầu làm video karaoke đầu tiên!",
        "settings" to "Cài đặt",
        "settings_sub" to "Tùy chỉnh hệ thống & hiển thị",
        "usage_notes" to "Lưu ý sử dụng",
        "usage_notes_title" to "LƯU Ý SỬ DỤNG",
        "usage_notes_en_title" to "Usage Notes",
        "usage_notes_body_vn" to "Đây là phần mềm offline và không kết nối với internet. Bên cạnh đó, đây cũng là một phần mềm mã nguồn mở được đăng tải trên GitHub. Bên cạnh đó, nếu bạn gặp vấn đề bản quyền từ nghệ sĩ, hãng đĩa hay nhà phân phối nhạc (lưu ý: nhà phân phối và nền tảng phát nhạc là khác nhau) thì chúng tôi sẽ không chịu trách nhiệm cho vấn đề này. Chúng tôi cũng khuyến khích người dùng tạo ra các bản tùy chỉnh của riêng mình để phần mềm có thể phát triển.",
        "usage_notes_body_en" to "This is offline software that does not connect to the internet. It is also open-source software hosted on GitHub. Please note that we bear no responsibility for any copyright issues arising from artists, record labels, or music distributors (note: distributors and music streaming platforms are distinct entities). We encourage users to create their own customizations to help the software evolve.",
        "continue" to "Tiếp tục",
        "continue_countdown" to "Tiếp tục (%ds)",
        "do_not_show_again" to "Không hiển thị lại lần sau",
        "close" to "Đóng",
        "back" to "Quay lại",
        "theme" to "Giao diện",
        "theme_system" to "Mặc định hệ thống",
        "theme_dark" to "Nền tối",
        "theme_light" to "Nền sáng",
        "language" to "Ngôn ngữ",
        "export_folder" to "Vị trí xuất Video & SRT/LRC",
        "export_folder_desc" to "Video MP4 -> Movies, Phụ đề (SRT/ASS/LRC) -> Documents",
        "change_folder" to "Đổi thư mục",
        "folder_name_label" to "Tên thư mục xuất",
        "default_soundfont" to "SoundFont (.sf2) mặc định",
        "default_soundfont_desc" to "Chọn soundfont tùy chỉnh cho bộ tổng hợp MIDI",
        "select_soundfont" to "Chọn SoundFont (.sf2)",
        "reset_soundfont" to "Khôi phục mặc định",
        "show_usage_notes_startup" to "Hiển thị lưu ý khi mở ứng dụng",
        "show_waveform_setting" to "Hiển thị sóng âm thanh & Piano Roll",
        "show_waveform_desc" to "Bật/tắt thanh sóng âm trong timeline để tối ưu không gian cho lời",
        "waveform_toggle_btn" to "Sóng âm",
        "waveform_on" to "Bật",
        "waveform_off" to "Tắt",
        
        // Editor tabs
        "tab_lyrics" to "Nhập lời",
        "tab_sync" to "Đồng bộ",
        "tab_audio" to "Âm thanh",
        "tab_layout" to "Layout & Thời gian",
        "tab_style" to "Tùy biến",
        "tab_export" to "Xuất file",

        // Sync Tab
        "tap_rhythm" to "BẤM THEO\nNHỊP",
        "undo_word" to "Lùi 1 từ (Đồng bộ lại)",
        "undo_tooltip" to "Nhấn để quay lại từ trước nếu đồng bộ sai thời điểm",
        "sync_hint" to "Nhấn nút Đỏ theo nhịp nhạc để đồng bộ chữ vào timeline",
        "waiting_word" to "Từ đang chờ đồng bộ:",
        "all_synced" to "Đã đồng bộ hết",
        "progress" to "Tiến trình",
        "words" to "từ",
        "lines" to "dòng",
        "reset_sync" to "Reset Tất Cả",
        "play_first_warning" to "Hãy bấm phát nhạc trước khi đồng bộ!",
        "undo_toast" to "Đã lùi 1 từ & quay lại mốc thời gian!",

        // Lyrics Tab
        "edit_lyrics_header" to "SOẠN THẢO LỜI BÀI HÁT",
        "full_text_mode" to "Toàn Văn",
        "lines_mode" to "Từng Dòng",
        "save_and_split" to "Lưu & Phân Tách Từ",
        "paste_lyrics" to "Dán Lời",
        "format_lyrics" to "Chuẩn Hóa",
        "clear_lyrics" to "Xóa Lời",
        "lyrics_input_placeholder" to "Nhập hoặc dán lời bài hát tại đây...\nMỗi dòng là một câu hát.",
        "lyrics_saved_toast" to "Đã lưu lời bài hát & phân tách từ!",
        "lyrics_pasted_toast" to "Đã dán lời từ bộ nhớ tạm!",
        "clipboard_empty" to "Bộ nhớ tạm đang trống!",

        // Waveform & Piano Roll
        "waveform_stereo" to "Sóng âm Stereo",
        "waveform_left" to "L (Trái)",
        "waveform_right" to "R (Phải)",
        "piano_roll" to "Nốt nhạc Piano Roll",
        "channel_filter" to "Kênh",
        "channel_all" to "Tất cả",
        "channel_melody" to "Giai điệu",
        "channel_bass" to "Bass",
        "channel_chords" to "Hợp âm",
        "channel_drums" to "Trống (Ch 10)",

        // Audio Tab
        "audio_speed" to "Tốc độ phát",
        "pitch_shift" to "Tông giọng (Pitch Shift)",
        "semitones" to "nửa cung",
        "source_audio" to "Tệp âm thanh nguồn",
        "select_custom_audio" to "Chọn tệp MP3 / WAV / MIDI",
        "imported_soundfonts" to "SoundFont cho bài hát này",
        "default_synth" to "Bộ tổng hợp mặc định hệ thống",

        // Layout Tab
        "screen_preset" to "CẤU HÌNH MÀN HÌNH (SCREEN PRESET)",
        "layout_mode" to "CHẾ ĐỘ BỐ CỤC (LAYOUT MODE)",
        "mode_two_rows" to "2 Hàng Karaoke",
        "mode_one_row" to "1 Hàng Đơn",
        "mode_centered" to "Căn Giữa 2 Hàng",
        "row1_title" to "HÀNG 1 (CÂU LẺ / TOP ROW)",
        "row2_title" to "HÀNG 2 (CÂU CHẴN / BOTTOM ROW)",
        "align_left" to "Căn Trái",
        "align_center" to "Căn Giữa",
        "align_right" to "Căn Phải",
        "offset_y" to "Vị trí dọc (Offset Y)",
        "time_sync_title" to "CĂN CHỈNH THỜI GIAN HÁT (TIMING)",
        "step_in" to "Step In (Chuẩn bị hát)",
        "step_out" to "Step Out (Biến mất sau khi hát)",
        "global_shift" to "Độ lệch đồng bộ tổng thể (Global Shift)",
        "lead_in_signals" to "TÍN HIỆU ĐẾM NHỊP BÁO TRƯỚC (LEAD-IN)",
        "signal_dots" to "Số chấm đếm nhịp",
        "signal_color" to "Màu chấm đếm nhịp",
        "signal_duration" to "Thời gian báo trước",

        // Style Tab
        "style_font_title" to "FONT CHỮ VÀ KÍCH THƯỚC",
        "font_family" to "Kiểu Font",
        "font_size" to "Cỡ chữ",
        "idle_text_color" to "Màu chữ chờ hát (Idle)",
        "active_text_color" to "Màu chữ đang hát (Active)",
        "outline_stroke" to "VIỀN CHỮ (OUTLINE STROKE)",
        "stroke_width" to "Độ dày viền",
        "shadow_effect" to "BÓNG ĐỔ (SHADOW EFFECT)",
        "shadow_blur" to "Độ nhòe bóng",
        "background_type" to "NỀN VIDEO XUẤT",
        "bg_checkerboard" to "Nền Trong Suốt (Checkerboard)",
        "bg_green" to "Phông Xanh (Green Screen)",
        "bg_black" to "Nền Đen (Black)",
        "bg_gradient" to "Gradient Tím",

        // Export Tab
        "export_title" to "XUẤT VIDEO & PHỤ ĐỀ",
        "export_mp4" to "Xuất Video MP4 (1080p)",
        "export_mp4_desc" to "Render video karaoke hoàn chỉnh với hiệu ứng chạy chữ thời gian thực",
        "export_srt" to "Xuất phụ đề SRT",
        "export_srt_desc" to "Phụ đề đồng bộ theo câu chuẩn định dạng SubRip",
        "export_ass" to "Xuất phụ đề Karaoke ASS",
        "export_ass_desc" to "Phụ đề Advanced SubStation Alpha có mã k-timing từng từ",
        "export_lrc" to "Xuất lời LRC",
        "export_lrc_desc" to "Lời bài hát đồng bộ theo dòng cho các máy nghe nhạc",
        "exporting_dialog_title" to "Đang kết xuất tệp...",
        "export_success_title" to "Xuất tệp thành công!",
        "file_saved_at" to "Đã lưu tại:",
        "save_success" to "Đã lưu thành công!",
        "artist_label" to "Nghệ sĩ:",
        "title_label" to "Tên bài hát:",
        "create_project" to "Tạo dự án",
        "create_new_project_dialog" to "TẠO DỰ ÁN MỚI",
        "choose_preset" to "Chọn từ bài hát mẫu (tự động có nhạc & nốt):",
        "cancel" to "Hủy"
    )

    private val stringsEN = mapOf(
        "app_title" to "KARAOKE STUDIO",
        "app_subtitle" to "Professional Karaoke Maker",
        "new_project" to "New Project",
        "new_project_sub" to "Start creating a new Video or MIDI/KAR project",
        "recent_projects" to "RECENT PROJECTS",
        "projects_count" to "projects",
        "no_projects_title" to "No projects yet",
        "no_projects_desc" to "Click 'New Project' to create your first karaoke video!",
        "settings" to "Settings",
        "settings_sub" to "System preferences & display options",
        "usage_notes" to "Usage Notes",
        "usage_notes_title" to "USAGE NOTES",
        "usage_notes_en_title" to "Usage Notes",
        "usage_notes_body_vn" to "Đây là phần mềm offline và không kết nối với internet. Bên cạnh đó, đây cũng là một phần mềm mã nguồn mở được đăng tải trên GitHub. Bên cạnh đó, nếu bạn gặp vấn đề bản quyền từ nghệ sĩ, hãng đĩa hay nhà phân phối nhạc (lưu ý: nhà phân phối và nền tảng phát nhạc là khác nhau) thì chúng tôi sẽ không chịu trách nhiệm cho vấn đề này. Chúng tôi cũng khuyến khích người dùng tạo ra các bản tùy chỉnh của riêng mình để phần mềm có thể phát triển.",
        "usage_notes_body_en" to "This is offline software that does not connect to the internet. It is also open-source software hosted on GitHub. Please note that we bear no responsibility for any copyright issues arising from artists, record labels, or music distributors (note: distributors and music streaming platforms are distinct entities). We encourage users to create their own customizations to help the software evolve.",
        "continue" to "Continue",
        "continue_countdown" to "Continue (%ds)",
        "do_not_show_again" to "Do not show again",
        "close" to "Close",
        "back" to "Back",
        "theme" to "Theme",
        "theme_system" to "System Default",
        "theme_dark" to "Dark Mode",
        "theme_light" to "Light Mode",
        "language" to "Language",
        "export_folder" to "Video & Subtitles Export Path",
        "export_folder_desc" to "Video MP4 -> Movies, Subtitles (SRT/ASS/LRC) -> Documents",
        "change_folder" to "Change Folder",
        "folder_name_label" to "Export Folder Name",
        "default_soundfont" to "Default SoundFont (.sf2)",
        "default_soundfont_desc" to "Choose custom soundfont for MIDI synthesizer",
        "select_soundfont" to "Select SoundFont (.sf2)",
        "reset_soundfont" to "Reset to Default",
        "show_usage_notes_startup" to "Show usage notes on startup",
        "show_waveform_setting" to "Show Audio Waveform & Piano Roll",
        "show_waveform_desc" to "Toggle audio waveform display on timeline to optimize lyric workspace",
        "waveform_toggle_btn" to "Waveform",
        "waveform_on" to "ON",
        "waveform_off" to "OFF",

        // Editor tabs
        "tab_lyrics" to "Lyrics",
        "tab_sync" to "Sync Rhythm",
        "tab_audio" to "Audio",
        "tab_layout" to "Layout & Timing",
        "tab_style" to "Style & Font",
        "tab_export" to "Export",

        // Sync Tab
        "tap_rhythm" to "TAP\nRHYTHM",
        "undo_word" to "Undo 1 word (Re-sync)",
        "undo_tooltip" to "Click to step back if a word was timed incorrectly",
        "sync_hint" to "Tap the Red button to the rhythm to sync words onto the timeline",
        "waiting_word" to "Current word to sync:",
        "all_synced" to "All Synced",
        "progress" to "Progress",
        "words" to "words",
        "lines" to "lines",
        "reset_sync" to "Reset All",
        "play_first_warning" to "Please press play before syncing!",
        "undo_toast" to "Stepped back 1 word & timeline position!",

        // Lyrics Tab
        "edit_lyrics_header" to "LYRICS EDITOR",
        "full_text_mode" to "Full Text",
        "lines_mode" to "By Line",
        "save_and_split" to "Save & Split Words",
        "paste_lyrics" to "Paste",
        "format_lyrics" to "Format",
        "clear_lyrics" to "Clear",
        "lyrics_input_placeholder" to "Type or paste song lyrics here...\nEach line represents a musical phrase.",
        "lyrics_saved_toast" to "Lyrics saved and words separated!",
        "lyrics_pasted_toast" to "Pasted lyrics from clipboard!",
        "clipboard_empty" to "Clipboard is empty!",

        // Waveform & Piano Roll
        "waveform_stereo" to "Stereo Waveform",
        "waveform_left" to "L (Left)",
        "waveform_right" to "R (Right)",
        "piano_roll" to "MIDI Piano Roll",
        "channel_filter" to "Channel",
        "channel_all" to "All",
        "channel_melody" to "Melody",
        "channel_bass" to "Bass",
        "channel_chords" to "Chords",
        "channel_drums" to "Drums (Ch 10)",

        // Audio Tab
        "audio_speed" to "Playback Speed",
        "pitch_shift" to "Key / Pitch Shift",
        "semitones" to "semitones",
        "source_audio" to "Source Audio File",
        "select_custom_audio" to "Select MP3 / WAV / MIDI File",
        "imported_soundfonts" to "SoundFont for this Project",
        "default_synth" to "System Default Synthesizer",

        // Layout Tab
        "screen_preset" to "SCREEN RESOLUTION PRESET",
        "layout_mode" to "LAYOUT DISPLAY MODE",
        "mode_two_rows" to "2 Karaoke Rows",
        "mode_one_row" to "1 Single Row",
        "mode_centered" to "Centered 2 Rows",
        "row1_title" to "ROW 1 (ODD LINES / TOP ROW)",
        "row2_title" to "ROW 2 (EVEN LINES / BOTTOM ROW)",
        "align_left" to "Align Left",
        "align_center" to "Align Center",
        "align_right" to "Align Right",
        "offset_y" to "Vertical Position (Offset Y)",
        "time_sync_title" to "SINGING TIMING ADJUSTMENTS",
        "step_in" to "Step In (Preparation time)",
        "step_out" to "Step Out (Disappear duration)",
        "global_shift" to "Global Timing Shift",
        "lead_in_signals" to "LEAD-IN COUNTDOWN SIGNALS",
        "signal_dots" to "Countdown Dots",
        "signal_color" to "Signal Color",
        "signal_duration" to "Lead-in Duration",

        // Style Tab
        "style_font_title" to "TYPOGRAPHY & SIZE",
        "font_family" to "Font Family",
        "font_size" to "Font Size",
        "idle_text_color" to "Idle Text Color",
        "active_text_color" to "Singing Text Color (Active)",
        "outline_stroke" to "OUTLINE STROKE",
        "stroke_width" to "Outline Thickness",
        "shadow_effect" to "SHADOW EFFECT",
        "shadow_blur" to "Shadow Blur Radius",
        "background_type" to "VIDEO BACKGROUND TYPE",
        "bg_checkerboard" to "Transparent (Checkerboard)",
        "bg_green" to "Green Screen (Chroma Key)",
        "bg_black" to "Solid Black",
        "bg_gradient" to "Purple Gradient",

        // Export Tab
        "export_title" to "EXPORT VIDEO & SUBTITLES",
        "export_mp4" to "Export MP4 Video (1080p)",
        "export_mp4_desc" to "Render complete karaoke video with real-time text highlight effects",
        "export_srt" to "Export SRT Subtitles",
        "export_srt_desc" to "SubRip synchronized subtitles per phrase",
        "export_ass" to "Export ASS Karaoke Subtitles",
        "export_ass_desc" to "Advanced SubStation Alpha with syllable k-timing tags",
        "export_lrc" to "Export LRC Lyrics",
        "export_lrc_desc" to "Line synchronized lyrics for media players",
        "exporting_dialog_title" to "Rendering file...",
        "export_success_title" to "Exported Successfully!",
        "file_saved_at" to "Saved at:",
        "save_success" to "Saved successfully!",
        "artist_label" to "Artist:",
        "title_label" to "Song Title:",
        "create_project" to "Create Project",
        "create_new_project_dialog" to "CREATE NEW PROJECT",
        "choose_preset" to "Choose from preset songs (auto filled):",
        "cancel" to "Cancel"
    )

    fun get(key: String, lang: Language): String {
        return when (lang) {
            Language.VN -> stringsVN[key] ?: stringsEN[key] ?: key
            Language.EN -> stringsEN[key] ?: stringsVN[key] ?: key
        }
    }
}
